# Generated by Django 4.2.19 on 2025-05-16 15:07

from django.db import migrations, models
import fixit_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_app', '0002_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[fixit_app.models.validate_year]),
        ),
    ]
